name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu_lastest
    steps:
      - uses: actions/chekout@v2
      
      - name: Run a one line script
        run: echo Hello, world!
        
      - name: Run a multiline script
        run: |
          echo Add other options to build;
          echo test and deploy your project
